import { Poppins } from "next/font/google";
import "./globals.css";

const inter = Poppins({ weight: ["400", "700"], subsets: ["latin"] });

export const metadata = {
  title: "4-A Chat Open Ai",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
